# Form implementation generated from reading ui file 'executar.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(759, 517)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalFrame = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalFrame = QtWidgets.QFrame(self.verticalFrame)
        self.horizontalFrame.setEnabled(True)
        self.horizontalFrame.setMinimumSize(QtCore.QSize(0, 40))
        self.horizontalFrame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.horizontalFrame)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_2.addWidget(self.textBrowser)
        self.pushAbrir = QtWidgets.QPushButton(self.horizontalFrame)
        self.pushAbrir.setObjectName("pushAbrir")
        self.horizontalLayout_2.addWidget(self.pushAbrir)
        self.verticalLayout.addWidget(self.horizontalFrame)
        self.treeWidget = QtWidgets.QTreeWidget(self.verticalFrame)
        self.treeWidget.setObjectName("treeWidget")
        self.verticalLayout.addWidget(self.treeWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushIniciar = QtWidgets.QPushButton(self.verticalFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushIniciar.setFont(font)
        self.pushIniciar.setObjectName("pushIniciar")
        self.horizontalLayout_3.addWidget(self.pushIniciar)
        self.pushParar = QtWidgets.QPushButton(self.verticalFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushParar.setFont(font)
        self.pushParar.setObjectName("pushParar")
        self.horizontalLayout_3.addWidget(self.pushParar)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addWidget(self.verticalFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushAbrir.setText(_translate("MainWindow", "Abrir"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Testcase"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Função"))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "Resultado"))
        self.pushIniciar.setText(_translate("MainWindow", "Iniciar"))
        self.pushParar.setText(_translate("MainWindow", "Parar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
